// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: proto/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthInter_Login_FullMethodName = "/auth.AuthInter/Login"
	AuthInter_Info_FullMethodName  = "/auth.AuthInter/Info"
)

// AuthInterClient is the client API for AuthInter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthInterClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
	Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRes, error)
}

type authInterClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthInterClient(cc grpc.ClientConnInterface) AuthInterClient {
	return &authInterClient{cc}
}

func (c *authInterClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, AuthInter_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authInterClient) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRes, error) {
	out := new(InfoRes)
	err := c.cc.Invoke(ctx, AuthInter_Info_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthInterServer is the server API for AuthInter service.
// All implementations must embed UnimplementedAuthInterServer
// for forward compatibility
type AuthInterServer interface {
	Login(context.Context, *LoginReq) (*LoginRes, error)
	Info(context.Context, *InfoReq) (*InfoRes, error)
	mustEmbedUnimplementedAuthInterServer()
}

// UnimplementedAuthInterServer must be embedded to have forward compatible implementations.
type UnimplementedAuthInterServer struct {
}

func (UnimplementedAuthInterServer) Login(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthInterServer) Info(context.Context, *InfoReq) (*InfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAuthInterServer) mustEmbedUnimplementedAuthInterServer() {}

// UnsafeAuthInterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthInterServer will
// result in compilation errors.
type UnsafeAuthInterServer interface {
	mustEmbedUnimplementedAuthInterServer()
}

func RegisterAuthInterServer(s grpc.ServiceRegistrar, srv AuthInterServer) {
	s.RegisterService(&AuthInter_ServiceDesc, srv)
}

func _AuthInter_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInterServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthInter_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInterServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthInter_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInterServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthInter_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInterServer).Info(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthInter_ServiceDesc is the grpc.ServiceDesc for AuthInter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthInter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthInter",
	HandlerType: (*AuthInterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthInter_Login_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _AuthInter_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth/auth.proto",
}
